### ISSUE TITLE
Start Error Unexpected token

### ISSUE THREAD

**Issue by shining01** [alessiodionisi/airplay-sonos#4]
Hello,

i have installed the newest Version.
I get the following errror. What is wrong?
Thanks

root@raspberrypi:~# airplay-sonos
/usr/local/lib/node_modules/airplay-sonos/index.js:8
sonos.search((device, model) => {
                             ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by alessiodionisi** [comment]
Node version?

**Comment by shining01** [comment]
node -v:
v0.12.6

**Comment by ghost** [comment]
same here!

**Comment by alessiodionisi** [comment]
Please use the latest stable version of nodejs (v6.9.4)

**Comment by shining01** [comment]
i have installed nodejs v.6.9.4

`
/usr/local/lib/node_modules/airplay-sonos/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: Module version mismatch. Expected 48, got 14.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/airplay-sonos/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
`
